const symbolNames: { [key: string]: string } = {
  MRFG3: "Marfrig Global Foods",
  PETR4: "Petrobras PN",
  PCAR4: "Pão de Açúcar PN",
  GOLL4: "Gol Linhas Aéreas Inteligentes PN",
  SUZB3: "Suzano Papel e Celulose",
  GOAU4: "Metalúrgica Gerdau PN",
  RADL3: "Raia Drogasil",
  RENT3: "Localiza",
  B3SA3: "B3 S.A. - Brasil, Bolsa, Balcão",
  VALE3: "Vale",
  ELET3: "Eletrobras ON",
  CMIG4: "Cemig PN",
  BBSE3: "BB Seguridade",
  JBSS3: "JBS",
  ELET6: "Eletrobras PNB",
  PETR3: "Petrobras ON",
  UGPA3: "Ultrapar Participações",
  SBSP3: "Sabesp",
  GGBR4: "Gerdau PN",
  CIEL3: "Cielo",
  VVAR3: "Via Varejo",
  BRFS3: "BRF",
  NATU3: "Natura",
  AZUL4: "Azul PN",
  BTOW3: "B2W Digital",
  MGLU3: "Magazine Luiza",
  LREN3: "Lojas Renner",
  ITUB4: "Itaú Unibanco PN",
  GNDI3: "NotreDame Intermédica",
  BRDT3: "Petrobras Distribuidora",
  RAIL3: "Rumo",
  BBAS3: "Banco do Brasil",
  ABEV3: "Ambev",
  ITSA4: "Itaúsa PN",
  KROT3: "Kroton",
  CCRO3: "CCR",
  CSNA3: "CSN",
  CVCB3: "CVC Brasil",
  BBDC4: "Bradesco PN",
  IRBR3: "IRB Brasil Resseguros",
};

export const getCompany = (symbol: string): string => {
  return symbolNames[symbol] || "";
};
